import { FirstLightScene } from './scene.js';

// ---------------------------------------------------------------- i18n
const STRINGS = {
  en: {
    'nav.viewer': 'Interactive', 'nav.renders': 'Cycles renders', 'nav.pipeline': 'Pipeline', 'nav.download': 'Download',
    'viewer.nowebgl': 'WebGL is unavailable in this browser; showing the Cycles still instead.',
    'viewer.loading': 'Loading scene',
    'viewer.title': 'Mount Fuji, the Chureito pagoda and sakura at first light',
    'viewer.hint': 'Drag to orbit · scroll to zoom · right-drag to pan',
    'ctl.reveal': '▶ Replay the 12 s reveal', 'ctl.wind': 'Wind', 'ctl.petals': 'Drifting petals', 'ctl.orbit': 'Auto orbit',
    'ctl.shadows': 'Shadows', 'ctl.reset': 'Back to the hero frame', 'ctl.full': 'Fullscreen',
    'intro.kicker': 'About the scene',
    'intro.title': 'A rebuildable Blender scene, and its real-time twin',
    'intro.p1': 'Everything — the five-tier Chureito pagoda, the descending stone stairs, vermilion railings, warm lanterns, six sakura tree types, the Fujiyoshida townscape and a Mount Fuji with radial gullies — is generated by one Python script from a fixed seed, with no external textures or scanned assets.',
    'intro.p2': 'The Cycles render uses AgX colour management and a low morning sun. The web build exports that same .blend to an 8 MB Draco glTF, rebuilds the 196 sakura trees with GPU instancing, moves the breeze into a vertex shader and relights the scene with Three.js lights and a gradient sky.',
    'facts.objects': 'Objects', 'facts.polys': 'Cycles polygons', 'facts.webtris': 'Web triangles / frame', 'facts.glb': 'glTF size', 'facts.frames': 'Camera animation', 'facts.seed': 'Random seed',
    'renders.kicker': 'Cycles / Metal', 'renders.title': 'Offline renders',
    'renders.stillcap': 'Frame 288 hero — 1920×1080, 96 samples, AgX.',
    'renders.videocap': '12-second animatic — 640×360 / 8 fps, 96 real Cycles frames sampled every third frame; for checking the dolly, the petals and the breeze.',
    'renders.h3': 'Camera',
    'renders.p1': 'A single 30 mm camera dollies slowly from the top of the stairs, travelling about 2.3 m and tilting up slightly over 12 seconds so the pagoda and the summit stay in frame throughout; validation.json records both projections at frames 1, 144 and 288.',
    'renders.p2': '“Replay the 12 s reveal” on the web uses the same start, end and tilt, then hands over to the orbit camera.',
    'pipe.kicker': 'From script to browser', 'pipe.title': 'Pipeline',
    'pipe.s1': 'Builds 12 collections headlessly with the bpy module: terrain, railings, the five-tier pagoda, lanterns, sakura, evergreens, the town, Fuji, drifting petals, sky and cameras. Procedural materials, the Geometry Nodes breeze and the 90 animated petals are all defined here.',
    'pipe.s2': 'Four presets — preview / still / animation / animatic — on Metal or CPU, resumable frame ranges, and a render_log.json per batch.',
    'pipe.s3': 'Reloads the .blend and asserts five separate roof tiers, zero external image dependencies, petal displacement, and where the finial and the summit project in camera at the key frames.',
    'pipe.s4': 'Leaves the source .blend untouched: subsamples blossoms per whole flower (34 % near, 11 % far), halves the needle sprays, flattens procedural shaders to PBR factors, applies modifiers, joins per collection and writes a Draco glTF plus export_manifest.json.',
    'pipe.s5': 'Three.js loads the glTF, batches the 392 sakura nodes into InstancedMesh, adds height-weighted wind in the vertex shader, rebuilds the sun and lantern lights, a gradient sky with aerial perspective, and tone-maps with AgX to match the offline look.',
    'dl.kicker': 'Source and outputs', 'dl.title': 'Download',
    'dl.note': 'The .blend ships as a GitHub Release asset — no Git LFS, no bandwidth quota; it can also be regenerated from build_scene.py.',
    'dl.web': 'web scene', 'dl.scripts': 'build, render, validate and export scripts',
    'foot.p': 'An art-directed interpretation, not a surveyed reconstruction. Photographs of Arakurayama Sengen Park were used as architectural and seasonal reference.',
  },
};
const ZH = {};
document.querySelectorAll('[data-i18n]').forEach(el => { ZH[el.dataset.i18n] = el.innerHTML; });
STRINGS.zh = ZH;

let lang = 'zh';
try { lang = localStorage.getItem('fsv-lang') || (navigator.language.startsWith('zh') ? 'zh' : 'en'); } catch {}
function applyLang(l) {
  lang = l;
  document.documentElement.lang = l === 'zh' ? 'zh-Hant' : 'en';
  document.querySelectorAll('[data-i18n]').forEach(el => { const s = STRINGS[l][el.dataset.i18n]; if (s !== undefined) el.innerHTML = s; });
  document.getElementById('langToggle').textContent = l === 'zh' ? 'EN' : '中';
  try { localStorage.setItem('fsv-lang', l); } catch {}
}
applyLang(lang);
document.getElementById('langToggle').addEventListener('click', () => applyLang(lang === 'zh' ? 'en' : 'zh'));

// ---------------------------------------------------------------- facts from manifests
fetch('assets/export_manifest.json').then(r => r.json()).then(m => {
  document.getElementById('factWebTris').textContent = (m.triangles_per_frame / 1e6).toFixed(1) + 'M';
  document.getElementById('factGlb').textContent = (m.bytes / 1e6).toFixed(1) + ' MB';
}).catch(() => {});
fetch('assets/scene_manifest.json').then(r => r.json()).then(m => {
  document.getElementById('factObjects').textContent = m.objects.toLocaleString();
}).catch(() => {});

// ---------------------------------------------------------------- viewer
const canvas = document.getElementById('stage');
const loader = document.getElementById('loader');
const bar = loader.querySelector('.bar');
const barFill = document.getElementById('barFill');
const pct = document.getElementById('loaderPct');
const fallback = document.getElementById('fallback');

function showFallback() {
  loader.classList.add('is-done');
  canvas.hidden = true;
  fallback.hidden = false;
  document.querySelector('.hud-bottom').hidden = true;
}

const hasWebGL = (() => { try { const c = document.createElement('canvas'); return !!(c.getContext('webgl2') || c.getContext('webgl')); } catch { return false; } })();
if (!hasWebGL) showFallback();

let view = null;
if (hasWebGL) {
  view = new FirstLightScene(canvas, {
    onProgress: p => {
      if (p < 0) { bar.classList.add('indeterminate'); pct.textContent = ''; return; }
      bar.classList.remove('indeterminate');
      barFill.style.width = (p * 100).toFixed(0) + '%';
      pct.textContent = (p * 100).toFixed(0) + '%';
    },
    onReady: () => { barFill.style.width = '100%'; setTimeout(() => loader.classList.add('is-done'), 250); },
    onError: showFallback,
  });

  const $ = id => document.getElementById(id);
  const toggle = (btn, fn) => btn.addEventListener('click', () => {
    const on = !btn.classList.contains('is-on');
    btn.classList.toggle('is-on', on); btn.setAttribute('aria-pressed', String(on)); fn(on);
  });
  $('btnReveal').addEventListener('click', () => view.startReveal());
  $('btnReset').addEventListener('click', () => view.resetView());
  toggle($('btnWind'), on => view.setWind(on));
  toggle($('btnPetals'), on => view.setPetals(on));
  toggle($('btnOrbit'), on => view.setOrbit(on));
  toggle($('btnShadows'), on => view.setShadows(on));
  $('btnFull').addEventListener('click', () => {
    const el = document.getElementById('viewer');
    if (document.fullscreenElement) document.exitFullscreen(); else el.requestFullscreen?.();
  });
  document.addEventListener('fullscreenchange', () => setTimeout(() => view.resize(), 60));

  const fpsEl = $('statFps'), trisEl = $('statTris'), callsEl = $('statCalls');
  setInterval(() => {
    const s = view.stats;
    if (!s.triangles) return;
    fpsEl.textContent = s.fps.toFixed(0) + ' fps';
    trisEl.textContent = (s.triangles / 1e6).toFixed(1) + 'M tris';
    callsEl.textContent = s.calls + ' calls';
  }, 500);

  // Don't burn the GPU while the viewer is scrolled off screen.
  new IntersectionObserver(([e]) => {
    if (!view.renderer) return;
    if (e.isIntersecting) view.renderer.setAnimationLoop(() => view.frame());
    else view.renderer.setAnimationLoop(null);
  }, { threshold: 0.05 }).observe(canvas);
}
